blog/account_app/urls.py
from django.urls import path

from .views import ArticleCreateView, AuthorArticlesListView, ArticleUpdateView

app_name = 'account_app'

urlpatterns = [
    path('new-article/', ArticleCreateView.as_view(), name='new_article'),
    path('edit-article/<int:pk>', ArticleUpdateView.as_view(), name='edit_article'),
    path('', AuthorArticlesListView.as_view(), name='my_articles'),
]

blog/auth_app/urls.py
from django.urls import path

from .views import RegisterCreateView, SignInLoginView, SingOutLogoutView
from .views import edit

app_name = 'auth_app'

urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', SignInLoginView.as_view(), name='login'),
    path('logout/', SingOutLogoutView.as_view(), name='logout'),
    path('edit/', edit, name='edit'),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('account/', include('account_app.urls', namespace='account_app')),
    path('', include('main_app.urls', namespace='main_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/main_app/urls.py
from django.urls import path

from .views import ArticleListView, IndexView, TagArticleListView, ArticleDetailView, SearchView, AddReviewView

app_name = 'main_app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<int:pk>/', ArticleListView.as_view(), name='articles'),
    path('category/<int:pk>/page/<int:page>/', ArticleListView.as_view(), name='page'),
    path('tag/<int:pk>/', TagArticleListView.as_view(), name='tag_articles'),
    path('tag/<int:pk>/page/<int:page>/', TagArticleListView.as_view(), name='page_tag'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('search/', SearchView.as_view(), name='search'),
    path('review/<int:pk>/', AddReviewView.as_view(), name='add_review'),

]

blog/templates/includes/inc_footer.html
{% load static %}

<footer class="footer">
    <div class="div contact">
        <div class="container table">
            <div class="col-8">
                <div class="row mb-2">
                    <div class="col-3 title">
                        <div class="footer-br">
                            <span>Ваш аккаунт</span>
                        </div>
                    </div>

                    <div class="col-3 title">
                        <div class="footer-br">
                            <span>Категории</span>
                        </div>
                    </div>
                    <div class="col-3 title">
                        <div class="footer-br">
                            <span>Информация</span>
                        </div>
                    </div>
                    <div class="col-3 title">
                        <div class="footer-br">
                            <span>Услуги</span>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-3">
                        <a href="#"><p>Профиль</p></a>
                        <a href="#"><p>Вход</p></a>
                        <a href="#"><p>Регистрация</p></a>
                    </div>
                    <div class="col-3">
                        {% for category in categories %}
                        <a href="#">
                            <p>{{ category.name }}</p>
                        </a>
                        {% endfor %}
                    </div>
                    <div class="col-3">
                        <a href="#"><p>Для авторов</p></a>
                        <a href="#"><p>Для компаний</p></a>
                        <a href="#"><p>Документы</p></a>
                        <a href="#"><p>Соглашение</p></a>
                    </div>
                    <div class="col-3">
                        <a href="#"><p>Реклама</p></a>
                        <a href="#"><p>Тарифы</p></a>
                        <a href="#"><p>Контент</p></a>
                        <a href="#"><p>Семинары</p></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="basement">
        <div class="container">
            <div class="years d-flex justify-content-between">
                <p><b>© 2021 ООО “Блог”.</b> Копирование запрещено</p>
                <p>Политика конфиденциальности</p>

            </div>
        </div>
    </div>


</footer>

blog/templates/includes/inc_navbar.html
{% load static %}

<div class="container-fluid fixed-top p-0">

    <div class="container-fluid menu">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-8 m-auto d-flex justify-content-between">
                    <div class="col-8 mx-0">
                    <a class="p-2 text-dark" href="{% url 'main_app:articles' 0 %}">Все категории</a>
                    {% for category in categories %}
                    <a class="p-2 text-dark" href="{% url 'main_app:articles' category.pk %}">{{ category.name }}</a>
                    {% endfor %}
                    </div>
                    <div class="col-4 search">

                        <form action="{% url 'main_app:search' %}" class="form-inline">
                            <img src="{% static 'img/search.svg' %}" alt="search">
                            <input type="text" name="search">
                        </form>
                    </div>

                </div>
                <div class="col-4 m-auto text-center">
                    {% if user.is_authenticated %}
                    <a class="p-2 text-dark" href="{% url 'auth_app:edit' %}">{{ user.username }}</a>
                    <a href="% url 'auth_app:edit' %}">
                        <img class="ava" src="{% get_media_prefix %}{{ user.bloguserprofile.avatar }}" alt="avatar">
                    </a>
                    <a class="p-2 text-dark" href="{% url 'auth_app:logout' %}">Выйти</a>
                    <a class="p-2 text-dark" href="{% url 'account_app:my_articles' %}">Статьи</a>
                    {% else %}
                    <a href="#">
                        <img class="anonim-ava" src="{% static 'img/frame-ava.svg' %}" alt="ava">
                    </a>
                    <a class="p-2 text-dark" href="{% url 'auth_app:login' %}">Войти</a>
                    {% endif %}

                    {% if user.is_superuser %}
                    <a class="p-2 text-dark" href="{% url 'admin:index' %}">Админка</a>
                    {% endif %}


                </div>

            </div>

        </div>
    </div>


</div>

blog/templates/includes/inc_pagination.html
<nav aria-label="Page navigation example">

    <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">

            {% if tag %}
            <a class="page-link text-dark" href="{% url 'main_app:page_tag' tag.pk page_obj.previous_page_number %}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
            {% else %}
            <a class="page-link text-dark" href="{% url 'main_app:page' category.pk page_obj.previous_page_number %}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
            {% endif %}

        </li>

        <li class="page-item">

            {% if tag %}
            <a class="page-link text-dark" href="{% url 'main_app:page_tag' tag.pk page_obj.previous_page_number %}">
                {{ page_obj.previous_page_number}}
            </a>
            {% else %}
            <a class="page-link text-dark" href="{% url 'main_app:page' category.pk page_obj.previous_page_number %}">
                {{ page_obj.previous_page_number}}
            </a>
            {% endif %}


        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link text-dark" href="" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

        <li class="page-item active"><a class="page-link text-dark" href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item">

            {% if tag %}
            <a class="page-link text-dark" href="{% url 'main_app:page_tag' tag.pk page_obj.next_page_number %}">
                {{ page_obj.next_page_number}}
            </a>
            {% else %}
            <a class="page-link text-dark" href="{% url 'main_app:page' category.pk page_obj.next_page_number %}">
                {{ page_obj.next_page_number}}
            </a>
            {% endif %}

        </li>
        <li class="page-item">

            {% if tag %}
            <a class="page-link text-dark" href="{% url 'main_app:page_tag' tag.pk page_obj.next_page_number %}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            {% else %}
            <a class="page-link text-dark" href="{% url 'main_app:page' category.pk page_obj.next_page_number %}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            {% endif %}

        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link text-dark" href="" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}

    </ul>
</nav>

blog/templates/includes/inc_reviews.html
{% load static %}

<hr>

<div class="container review">
    <div class="row">
        <h3 class="pl-3">Оставить отзыв о товаре:</h3>
    </div>

    <form action="{% url 'main_app:add_review' article.pk %}" method="post" id="formReview">
        {% csrf_token %}
        <input type="hidden" name="parent" id="parentComment" value="">
        <input type="hidden" name="user" value="{{ user.id }}">
        {{ form.text }}
        <div class="row justify-content-md-center">
            <input type="submit" class="form-control btn btn-secondary mt-4" value="Отправить">
        </div>
    </form>
</div>

<hr>

<div class="container review mb-4">
    <div class="row">
        <h3 class="pl-3">Читать отзывы:</h3>
    </div>

    {% for review in article.get_parent_reviews %}
    <hr>
    <div class="row">
        <div class="col-2 avatar">
            <img src="{% get_media_prefix %}{{ review.user.bloguserprofile.avatar }}"
                 alt="{{ review.user.username }}"
            >
        </div>
        <div class="col-8">
            <h5>{{ review.user.username }}</h5>
            <p>{{ review.text }}</p>
            <a href="#formReview" onclick="addReview('{{ review.user.username }}', {{ review.id }})">
                Ответить
            </a>
        </div>
    </div>

    {% for rev in review.reviews_set.all %}
    <div class="row ml-5 mt-3">
        <div class="col-2 avatar">
            <img src="{% get_media_prefix %}{{ rev.user.bloguserprofile.avatar }}" alt="{{ rev.user.username }}">
        </div>
        <div class="col-8">
            <h5>{{ rev.user.username }}</h5>
            <p>{{ rev.text }}</p>
        </div>
    </div>
    {% endfor %}

    {% empty %}
    <div class="row justify-content-center my-5">
        <h5>Ваш отзыв может быть первым</h5>
    </div>

    {% endfor %}

</div>
<script>
    function addReview(name, id) {
        document.getElementById('parentComment').value = id;
        document.getElementById('comment').innerText = `${name}, `;
    }

</script>

blog/templates/includes/inc_sidebar.html
<div class="sidebar mx-auto">
    <div class="sidebar-header py-3 px-3">ЧИТАЮТ СЕЙЧАС</div>
    {% for article in reading %}
    <a href="{% url 'main_app:article' article.pk %}">
        <div class="sidebar-item px-3">
            <div class="br py-3">
                {{ article.title }}
            </div>
        </div>
    </a>
    {% endfor %}


</div>