blog/auth_app/urls.py
from django.urls import path

from .views import RegisterCreateView, SignInLoginView, SingOutLogoutView
from .views import edit

app_name = 'auth_app'

urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', SignInLoginView.as_view(), name='login'),
    path('logout/', SingOutLogoutView.as_view(), name='logout'),
    path('edit/', edit, name='edit'),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('account/', include('account_app.urls', namespace='account_app')),
    path('', include('main_app.urls', namespace='main_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/auth_app/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class BlogUser(AbstractUser):
    """Модель пользователя"""
    email = models.EmailField(unique=True)


class BlogUserProfile(models.Model):
    """Профиль пользователя"""
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = ((MALE, 'М'), (FEMALE, 'Ж'))

    user = models.OneToOneField(settings.AUTH_USER_MODEL, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    gender = models.CharField('Пол', max_length=1, choices=GENDER_CHOICES, blank=True)
    obout = models.TextField('О себе', blank=True)
    date_of_birth = models.DateTimeField('Дата рождение', blank=True, null=True)
    avatar = models.ImageField('Аватар', upload_to='avatars', default='avatar/default_avatar.jpg')

    @receiver(post_save, sender=BlogUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            BlogUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=BlogUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.bloguserprofile.save()

    class Meta:
        verbose_name = 'Профайл'
        verbose_name_plural = 'Профайлы'

    def __str__(self):
        return f'Profile - {self.user}'

blog/auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from .models import BlogUser, BlogUserProfile


class BlogUserCreationForm(UserCreationForm):
    """Форма регистрации нового пользователя"""
    class Meta:
        model = BlogUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class BlogUserLoginForm(AuthenticationForm):
    """Форма входа в учетную запись пользователя"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class BlogUserEditForm(UserChangeForm):
    """Форма редактирования учетной записи пользователя"""
    class Meta:
        model = BlogUser
        fields = ('username', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class BlogUserProfileEditForm(UserChangeForm):
    """"Форма редактирования профиля пользователя"""
    class Meta:
        model = BlogUserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

blog/auth_app/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from .forms import BlogUserCreationForm, BlogUserLoginForm, BlogUserEditForm, BlogUserProfileEditForm


class RegisterCreateView(CreateView):
    """Регистрация нового пользователя"""
    template_name = 'auth_app/register.html'
    form_class = BlogUserCreationForm
    success_url = reverse_lazy('auth_app:login')


class SignInLoginView(LoginView):
    """Вход в учетную запись пользователя"""
    authentication_form = BlogUserLoginForm
    template_name = 'auth_app/login.html'


class SingOutLogoutView(LogoutView):
    """Выход из учетной записи пользователя"""


@transaction.atomic
def edit(request):
    """Редактирование профиля пользователя"""
    if request.method == 'POST':
        edit_form = BlogUserEditForm(request.POST, instance=request.user)
        profile_form = BlogUserProfileEditForm(request.POST, request.FILES, instance=request.user.bloguserprofile)

        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth_app:edit'))

    else:
        edit_form = BlogUserEditForm(instance=request.user)
        profile_form = BlogUserProfileEditForm(instance=request.user.bloguserprofile)

    context = {
        'edit_form': edit_form,
        'profile_form': profile_form
    }
    return render(request, 'auth_app/edit.html', context)

blog/templates/auth_app/edit.html
{% extends 'base.html' %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block content %}

    <div class="container edit">
        <form action="{% url 'auth_app:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" class="form-control mb-5 btn btn-secondary" value="Сохранить">
        </form>
    </div>

{% endblock %}

blog/templates/auth_app/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}

<div class="container login">


    <form action="{% url 'auth_app:login' %}" method="post">
        {% csrf_token %}

        {% if next %}
            {% if 'review' in next %}
            <h5 class="text-center mb-4">Для добавления отзыва необходимо авторизоваться</h5>
            {% else %}
            <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
        {% endif %}

        {{ form.as_p }}

        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Войти">
    </form>

    <button class="form-control mt-5 btn btn-light text-white">
        <a href="{% url 'auth_app:register' %}">Зарегистрироваться</a>
    </button>

</div>

{% endblock %}

blog/templates/auth_app/register.html
{% extends 'base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
<div class="container login">
    <form method="post" action="{% url 'auth_app:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Зарегистрироваться">
    </form>
</div>
{% endblock %}