blog/account_app/urls.py
from django.urls import path

from .views import ArticleCreateView, AuthorArticlesListView, ArticleUpdateView

app_name = 'account_app'

urlpatterns = [
    path('new-article/', ArticleCreateView.as_view(), name='new_article'),
    path('edit-article/<int:pk>', ArticleUpdateView.as_view(), name='edit_article'),
    path('', AuthorArticlesListView.as_view(), name='my_articles'),
]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('account/', include('account_app.urls', namespace='account_app')),
    path('', include('main_app.urls', namespace='main_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/main_app/urls.py
from django.urls import path

from .views import ArticleListView, IndexView, TagArticleListView, ArticleDetailView, SearchView, AddReviewView

app_name = 'main_app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<int:pk>/', ArticleListView.as_view(), name='articles'),
    path('category/<int:pk>/page/<int:page>/', ArticleListView.as_view(), name='page'),
    path('tag/<int:pk>/', TagArticleListView.as_view(), name='tag_articles'),
    path('tag/<int:pk>/page/<int:page>/', TagArticleListView.as_view(), name='page_tag'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('search/', SearchView.as_view(), name='search'),
    path('review/<int:pk>/', AddReviewView.as_view(), name='add_review'),

]

blog/account_app/models.py
from django.db import models

# Create your models here.

blog/account_app/forms.py
from django import forms

from main_app.models import Article


class ArticleCreationForm(forms.ModelForm):
    """"Форма написания новой статьи"""

    class Meta:
        model = Article
        fields = ('title', 'category', 'tags', 'poster', 'short_desc', 'text', 'draft')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

blog/account_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from account_app.forms import ArticleCreationForm
from main_app.models import Tag, Article


class AuthorArticlesListView(LoginRequiredMixin, ListView):
    """Список статей пользователя"""
    template_name = 'account_app/my_articles.html'

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user).order_by('draft')


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """Написание новой статьи"""
    template_name = 'account_app/new_article.html'
    form_class = ArticleCreationForm

    def post(self, request, *args, **kwargs):
        form = ArticleCreationForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            tags = form.cleaned_data['tags']
            article.save()
            if len(tags):
                for item in tags:
                    tag = Tag.objects.get(pk=item.pk)
                    article.tags.add(tag)
            return redirect(reverse('account_app:my_articles'))
        return redirect(reverse('account_app:new_article'))


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'account_app/edit_article.html'
    success_url = reverse_lazy('account_app:my_articles')

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs['pk'])
        if request.user != article.author:
            return redirect(reverse('main_app:index'))
        return super().get(request, *args, **kwargs)

blog/templates/account_app/edit_article.html
{% extends 'base.html' %}

{% block title %}
    Написание статьи
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-3 text-center">Редактирование статьи</h1>
    <form method="post" enctype="multipart/form-data" class="mb-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Сохранить">
    </form>
</div>
{% endblock %}

blog/templates/account_app/my_articles.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Мои статьи
{% endblock %}

{% block content %}

<div class="container">

    <div class="row my-4 align-items-center my-articles">

        <div class="col text-center">
            <h5>Наименование</h5>
        </div>

        <div class="col text-center">
            <h5>Теги</h5>
        </div>

        <div class="col text-center">
            <h5>Постер</h5>
        </div>

        <div class="col text-center">
            <h5>Дата публикации</h5>
        </div>

        <div class="col text-center">
            <h5>Дата редактирования</h5>
        </div>

        <div class="col text-center">
            <h5>Опубликована</h5>
        </div>

        <div class="col-1 text-center">
            <a href="{% url 'account_app:new_article' %}">
                <button class="btn btn-secondary">Написать</button>
            </a>
        </div>

    </div>

    {% if object_list.count %}

    {% for article in object_list %}

    <div class="row my-4 align-items-center">

        <div class="col">
            <a href="{% url 'main_app:article' article.pk %}">
                <p>{{ article.title }}</p>
            </a>
        </div>

        <div class="col">
            {% for tag in article.tags.all %}
            <a href="{% url 'main_app:tag_articles' tag.pk %}">{{ tag.name }},&ensp;</a>
            {% endfor %}
        </div>

        <div class="col">
            <img src="{% get_media_prefix %}{{ article.poster }}" alt="poster">
        </div>
        <div class="col">
            <p>{{ article.pub_date }}</p>
        </div>
        <div class="col">
            <p>{{ article.last_edit }}</p>
        </div>
        <div class="col">
            {% if article.draft %}
            <p>нет</p>
            {% else %}
            <p>да</p>
            {% endif %}
        </div>
        <div class="col-1">
            <a href="{% url 'account_app:edit_article' article.pk %}"><button class="btn btn-secondary">Редактировать</button></a>
        </div>


    </div>

    {% endfor %}

    {% else %}

    <h1 class="text-center mt-5">У вас пока нет статей!</h1>

    {% endif %}


</div>

{% endblock %}

blog/templates/account_app/new_article.html
{% extends 'base.html' %}

{% block title %}
    Написание статьи
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-3 text-center">Написание статьи</h1>
    <form method="post" action="{% url 'account_app:new_article' %}" enctype="multipart/form-data" class="mb-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Сохранить">
    </form>
</div>
{% endblock %}